---
- name: initialize the cluster
  shell: kubeadm init --apiserver-cert-extra-sans=217.28.228.119 --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint=217.28.228.119 --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
    args:
      chdir: /home/appuser
      creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: appuser
  file:
    path: /home/appuser/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/appuser/.kube/config
    remote_src: yes
    owner: appuser

- name: copy calico.yml
  template:
    src: calico.yaml.j2
    dest: /home/appuser/calico.yaml
      owner: appuser
      groups: appuser

- name: install Pod network
  become: yes
  become_user: appuser
    shell: kubectl apply -f calico.yaml >> pod_network_setup.txt
    args:
      chdir: /home/appuser
      creates: pod_network_setup.txt