- name: Download the Calico networking manifest for the Kubernetes API datastore
  become: yes
  become_user: ubuntu
  get_url:
    url: https://docs.projectcalico.org/manifests/calico.yaml
    dest: $HOME/calico.yaml
    mode: "0440"

- name: CALICO_IPV4POOL_CIDR
  become: yes
  become_user: ubuntu
  replace:
    path: $HOME/calico.yaml
    regexp: "([ ]*)(# )(-.*(CALICO_IPV4POOL_CIDR))"
    replace: '\1\3\n\1  value: "10.244.0.0/16"'

- name: Init cluster
  become: yes
  become_user: ubuntu
  shell: kubectl apply -f calico.yaml
