- name: initialize the cluster
  shell: kubeadm init --apiserver-cert-extra-sans=84.252.129.241 --apiserver-advertise-address=0.0.0.0 --control-plane-endpoint=84.252.129.241 --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt

- name: Fetch txt
  fetch:
    src: ./cluster_initialized.txt 
    dest: ../files/cluster_initialized.txt
    flat: yes

- name: create .kube directory
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: ubuntu