global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#yaroslav_veselukha'