FROM alpine:3.9

RUN apk update \
    && apk --no-cache --update add ruby-full \
            ruby-dev \
    && apk --no-cache --update add build-base \
    && gem install bundler:1.17.2 --no-ri --no-rdoc


WORKDIR /app
COPY Gemfile* ./
RUN bundle install
COPY . .

ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments

CMD ["puma"]
