version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    container_name: reddit_mongodb
    volumes:
      - post_db:/data/db
    networks:
      reddit_back:
        aliases: 
          - post_db
          - comment_db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    container_name: reddit-ui
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    container_name: reddit-post
    networks:
      - reddit_back
      - reddit_front
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    container_name: reddit-comment
    networks:
      - reddit_back
      - reddit_front
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
