version: '3.3'
services:

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks: 
      - reddit_front

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks: 
      - reddit_front
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks: 
      - reddit_front
    
  mongodb-exporter:
    user: root
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    networks:
      - reddit_front
      - reddit_back
    command:
      - '--mongodb.uri=post_db:27017'
      - '--web.listen-address=:9111'
        
  blackbox-exporter:
    user: root
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    networks:
      - reddit_front
      - reddit_back

  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - reddit_front      

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
    - 9093:9093
    networks:
      - reddit_front  

volumes:
  prometheus_data:
  grafana_data:
   
networks:
  reddit_front:
  reddit_back:
    