version: '3.3'
services:

  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    container_name: reddit_mongodb
    volumes:
      - post_db:/data/db
    networks:
      - reddit_back

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    container_name: reddit-ui
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    container_name: reddit-post
    networks:
      - reddit_back
      - reddit_front

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    container_name: reddit-comment
    networks:
      - reddit_back
      - reddit_front

volumes:
  post_db:

networks:
  reddit_front:
  reddit_back:
