version: '3.3'
services:

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks: 
      - prometheus
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  post_db:
    image: mongo:${MONGO_IMAGE_VERSION}
    container_name: reddit_mongodb
    volumes:
      - post_db:/data/db
    networks:
      - reddit_back

  ui:
    #build: ./ui
    image: ${USERNAME}/ui:${UI_IMAGE_VERSION}
    container_name: reddit-ui
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - reddit_front

  post:
    #build: ./post-py
    image: ${USERNAME}/post:${POST_IMAGE_VERSION}
    container_name: reddit-post
    networks:
      - reddit_back
      - reddit_front

  comment:
    #build: ./comment
    image: ${USERNAME}/comment:${COMMENT_IMAGE_VERSION}
    container_name: reddit-comment
    networks:
      - reddit_back
      - reddit_front


  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks: 
      - reddit_front
      - prometheus

  mongodb-exporter:
    user: root
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    networks:
      - reddit_front
      - reddit_back
    command:
      - '--mongodb.uri=post_db:27017'
      - '--web.listen-address=:9111'
    
  blackbox-exporter:
    user: root
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    networks:
      - reddit_front
      - reddit_back

        volumes:
  post_db:
  prometheus_data:

networks:
  reddit_front:
  reddit_back:
  prometheus:
